### ISSUE TITLE
Translation German 

### ISSUE THREAD

**Issue by KarstenW76** [MythicPalette/simpler-quests#2]
Hi, I really like your Quest Tracker, so I directly created a German translation. Would you add it to your module, so others participate also?

Please find the json attached.
[de.json](https://github.com/user-attachments/files/17176820/de.json)

**Comment by MythicPalette** [comment]
I'll take a look for sure! The more languages, the more people can enjoy my module. I appreciate the help.

**Comment by MythicPalette** [comment]
Reviewing the language file and my code in general made me realize I forgot to add a lot of keys to the localization file, so thank you for that! I'm going to get these other keys added into the file. Did you want to help me translate the missing keys as well?

**Comment by MythicPalette** [comment]
Ok, I translated the remaining keys with ChatGPT and then checked each one with Google Translate. I know, I know. Neither of those are very trustworthy with translations. If you see any translation errors, just let me know in another ticket and I'll fix those.

**Comment by KarstenW76** [comment]
Awesome, yes, I‘ll validate and correct whats needed, thank you!
