### ISSUE TITLE
Ripper's Simple Quest integration

### ISSUE THREAD

**Issue by talesparrow** [MythicPalette/simpler-quests#3]
Would love to see your tracker integrate with Ripper's SimpleQuest module.  It currently lacks a tracker.  https://theripper93.com/module/simple-quest

**Comment by MythicPalette** [comment]
Unfortunately, that is a paid module (it requires his Patreon subscription). Maybe try posting a feature request for a tracker on his module? Without owning his module, I couldn't even begin to look at integrating with it.
