### ISSUE TITLE
Macro to open/close Simpler Quests (toggle)

### ISSUE THREAD

**Issue by tagnullde** [MythicPalette/simpler-quests#5]
Hey, thanks for the great module. A godsend for my Pathfinder 2e Kingmaker Campaign.

I have to run the module in floating mode though, because the button for the docked mode is almost always hidden behind the status conditions of my players. It would be cool to let the players open the tracker via a macro that calls the same function as the sidebar menu would. It would save them a click or two and I could integrate it in our Dynamic Tiles Setup (I have a landing page with elements the players can click, like a game menu. And adding the quest-log there would be a great addition.

Thanks in advance.

**Comment by MythicPalette** [comment]
I can absolutely take a look into this! I already pretty much know how I would do it so I could potentially have this done today if things go well.

**Comment by MythicPalette** [comment]
So, this has turned into a full blown macro API implementation. The API is not complete yet but, once it is done, I'll put a wiki documentation together for it.

**Comment by MythicPalette** [comment]
Ok, I believe the API update is ready to ship soon. I just need to test it, pack it up, and upload it. Here is the promised documentation on how to use it: https://github.com/MythicPalette/simpler-quests/wiki/API

**Comment by tagnullde** [comment]
Wow. You've outdone yourself. Thank you very much. :)
