### ISSUE TITLE
Module updates itself to same version

### ISSUE THREAD

**Issue by r-valyar** [MythicPalette/simpler-quests#7]
After the last update, the module updates itself to the same version, probably due to issue with the manifest file.
![image](https://github.com/user-attachments/assets/4da103d0-c97f-42aa-b074-137088a720b3)

**Comment by MythicPalette** [comment]
Definitely should not be happening. Let me take a peak at that manifest real quick...

**Comment by MythicPalette** [comment]
Ok, I believe I resolved the issue. I had the foundry version listed as "v0.1.6" and the manifest declared version "0.1.6". Just leaving out the `v` caused the issue. Go ahead and update it one more time to install the new manifest copy and that should resolve the issue. Sorry for the inconvenience.
